### PR TITLE
Fail fast on known invalid indexing directive fields

### LINKED ISSUE #178: Handle version differences with URL parameter fields
Certain document hash keys are "special" and get converted into URL parameters rather than being indexed with the document.

These fields are added to a document. They get pulled out and added to the query
string (rather than being passed in a a parameter to the index method). Any unknown underscore fields are ignored and indexed as usual.

https://github.com/github/elastomer-client/blob/9e96707e74ab890607f5cd795cf186a9af457898/lib/elastomer/client/docs.rb#L520

These URL parameters are different between versions. `_consistency` got re-implemented as `_wait_for_active_shards` and has different values, so it's not a direct mapping. 

Additionally, ES 5 no longer allows unknown URL parameters. So we need to not send it or force the caller to deal with the error. And vice-versa, there is a problem as well: if someone uses a new
parameter from ES 5, it will end up in a document as a field unless we pull it out and put it on the URL as a parameter (which ES 2 will ignore), or pull it out and ignore it.

We need to decide how to handle these differences in the library.

References:

* [ES 5 `wait_for_active_shards`](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-index_.html#index-wait-for-active-shards)
* [ES 2 `consistency`](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-index_.html#index-consistency)
* [Issue about the change](https://github.com/elastic/elasticsearch/issues/21804)

### PR DESCRIPTION
**Pull request by look**
Pull the different "special" fields that affect indexing into VersionSupport in
order to return a different Hash of parameter name/field name depending on the
client's version.

If a caller attempts to index a document with a known indexing directive field
that is not supported by the version of Elasticsearch, the client will fail fast
and not allow the document to be indexed.

Fixes #178.

### CODE REVIEW

**Comment by look** [comment]
With this change, tests are now passing against ES 5.6. 🎉

**Comment by elireisman** [comment]
No complaints here, looks great :shipit:

File: lib/elastomer/client/docs.rb [hunk 1]
```diff
@@ -534,10 +531,23 @@ def from_document( document )
...
+          # COMPATIBILITY
+          # Fail fast if a consumer is attempting to use an indexing parameter
+          # for a different version of Elasticsearch. Elasticsearch 5+ is strict
+          # about parameter names so we need to either ignore these (in which
+          # case they would be indexed with the document) or fail-fast.
+          # Elasticsearch 2.X will happily ignore unknown parameters, but we
+          # felt it was best to consistently fail fast.
+          client.version_support.unsupported_indexing_directives.each do |key, field|
+            if document.key?(field) || document.key?(field.to_sym)
+              raise IncompatibleVersionException, "Elasticsearch #{client.version} does not support the '#{key}' indexing parameter"
```
Comment (TwP) [inline lib/elastomer/client/docs.rb]: My thought here is that the `IncompatibleVersionException` should be used for features that are not available across both major versions of Elasticsearch that we support. For parameters, we should create a new `IllegalArgumentException` that is raised when an incompatible parameter is used. This mirrors the exception returned by Elasticsearch itself, and we will be using this exception across more and more the client library.

The distinction helps us know when a feature is just gone versus when a request needs a little tweaking.

Comment (look) [reply lib/elastomer/client/docs.rb]: Yeah, I agree. I'll create a new exception for this.

Comment (elireisman) [reply lib/elastomer/client/docs.rb]: this makes sense :+1:

**Comment by elireisman** [comment]
+1 for the new exception, will come in handy for the rest of this effort as @TwP mentioned
➡️ 🚢 ⬅️

**Comment by look** [comment]
woohoo!
